package org.chanki.examples.pojo;

import java.util.ArrayList;
import java.util.List;
import org.chanki.Json2Sheet;

public class PojoTest {
  public static void main(String[] args) throws Exception {
    List<User> userList = new ArrayList<>();
    userList.add(new User("noon_name", 21, "leader"));
    userList.add(new User("we_name", 21, "flew"));
    userList.add(new User("step_name", 21, "ran"));
    userList.add(new User("tried_name", 21, "tune"));
    userList.add(new User("character_name", 21, "plus"));
    userList.add(new User("major_name", 21, "paid"));
    userList.add(new User("development_name", 21, "spent"));
    userList.add(new User("shadow_name", 21, "naturally"));
    userList.add(new User("floating_name", 21, "elephant"));
    userList.add(new User("understanding_name", 21, "classroom"));
    userList.add(new User("situation_name", 21, "straw"));
    userList.add(new User("good_name", 21, "unhappy"));
    userList.add(new User("took_name", 21, "strange"));
    userList.add(new User("quickly_name", 21, "particular"));
    userList.add(new User("nervous_name", 21, "stronger"));
    userList.add(new User("could_name", 21, "read"));
    userList.add(new User("stairs_name", 21, "valley"));
    userList.add(new User("depend_name", 21, "here"));
    userList.add(new User("curve_name", 21, "bare"));
    userList.add(new User("command_name", 21, "sunlight"));
    userList.add(new User("still_name", 21, "lie"));
    userList.add(new User("pass_name", 21, "beginning"));
    userList.add(new User("hidden_name", 21, "design"));
    userList.add(new User("sun_name", 21, "flight"));
    userList.add(new User("basic_name", 21, "fence"));
    userList.add(new User("case_name", 21, "baby"));
    userList.add(new User("burn_name", 21, "stay"));
    userList.add(new User("progress_name", 21, "forest"));
    userList.add(new User("golden_name", 21, "split"));
    userList.add(new User("protection_name", 21, "yourself"));
    userList.add(new User("minute_name", 21, "husband"));
    userList.add(new User("book_name", 21, "post"));
    userList.add(new User("greatest_name", 21, "fireplace"));
    userList.add(new User("shaking_name", 21, "five"));
    userList.add(new User("pool_name", 21, "stronger"));
    userList.add(new User("curve_name", 21, "firm"));
    userList.add(new User("thus_name", 21, "flies"));
    userList.add(new User("bridge_name", 21, "although"));
    userList.add(new User("together_name", 21, "threw"));
    userList.add(new User("finest_name", 21, "express"));
    userList.add(new User("tiny_name", 21, "as"));
    userList.add(new User("moving_name", 21, "transportation"));
    userList.add(new User("struggle_name", 21, "fuel"));
    userList.add(new User("fifty_name", 21, "throat"));
    userList.add(new User("modern_name", 21, "wide"));
    userList.add(new User("declared_name", 21, "taste"));
    userList.add(new User("practice_name", 21, "nobody"));
    userList.add(new User("sun_name", 21, "ago"));
    userList.add(new User("angry_name", 21, "path"));
    userList.add(new User("series_name", 21, "happy"));
    userList.add(new User("our_name", 21, "sentence"));
    userList.add(new User("drink_name", 21, "toward"));
    userList.add(new User("physical_name", 21, "husband"));
    userList.add(new User("tail_name", 21, "fact"));
    userList.add(new User("broke_name", 21, "satisfied"));
    userList.add(new User("factory_name", 21, "dry"));
    userList.add(new User("pack_name", 21, "think"));
    userList.add(new User("two_name", 21, "main"));
    userList.add(new User("sentence_name", 21, "water"));
    userList.add(new User("pilot_name", 21, "develop"));
    userList.add(new User("wave_name", 21, "excellent"));
    userList.add(new User("hide_name", 21, "vegetable"));
    userList.add(new User("mirror_name", 21, "recently"));
    userList.add(new User("older_name", 21, "powerful"));
    userList.add(new User("produce_name", 21, "tower"));
    userList.add(new User("molecular_name", 21, "fifty"));
    userList.add(new User("throw_name", 21, "term"));
    userList.add(new User("track_name", 21, "land"));
    userList.add(new User("being_name", 21, "task"));
    userList.add(new User("treated_name", 21, "newspaper"));
    userList.add(new User("stomach_name", 21, "property"));
    userList.add(new User("safe_name", 21, "hope"));
    userList.add(new User("single_name", 21, "generally"));
    userList.add(new User("individual_name", 21, "wash"));
    userList.add(new User("buy_name", 21, "customs"));
    userList.add(new User("evening_name", 21, "coat"));
    userList.add(new User("live_name", 21, "strange"));
    userList.add(new User("made_name", 21, "tiny"));
    userList.add(new User("by_name", 21, "desk"));
    userList.add(new User("lack_name", 21, "fruit"));
    userList.add(new User("fought_name", 21, "show"));
    userList.add(new User("till_name", 21, "gravity"));
    userList.add(new User("weight_name", 21, "shorter"));
    userList.add(new User("flies_name", 21, "deer"));
    userList.add(new User("faster_name", 21, "bus"));
    userList.add(new User("fort_name", 21, "unit"));
    userList.add(new User("hung_name", 21, "diameter"));
    userList.add(new User("hidden_name", 21, "are"));
    userList.add(new User("particles_name", 21, "correctly"));
    userList.add(new User("pile_name", 21, "fort"));
    userList.add(new User("pretty_name", 21, "nearly"));
    userList.add(new User("girl_name", 21, "tightly"));
    userList.add(new User("progress_name", 21, "airplane"));
    userList.add(new User("safety_name", 21, "lady"));
    userList.add(new User("buy_name", 21, "call"));
    userList.add(new User("sand_name", 21, "leader"));
    userList.add(new User("water_name", 21, "special"));
    userList.add(new User("active_name", 21, "inch"));
    userList.add(new User("larger_name", 21, "finest"));
    userList.add(new User("physical_name", 21, "height"));
    userList.add(new User("bare_name", 21, "milk"));

    Json2Sheet.fromPOJO(userList).saveExcel("userExcel.xlsx");
  }
}
